# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Pod
metadata:
  name: sglang-benchmark
spec:
  containers:
  - name: sglang-benchmark-container
    image: python:3.9-slim
    command: ["/bin/bash", "-c"]
    args:
    - |
      set -ex
      apt-get update && apt-get install -y git
      git clone -b v0.5.2 https://github.com/sgl-project/sglang.git
      cd sglang
      pip install --upgrade pip
      pip install protobuf aiohttp numpy requests tqdm transformers
      python3 python/sglang/bench_serving.py \
        --host=$(IP) \
        --port=$(PORT) \
        --dataset-name='generated-shared-prefix' \
        --model=$(MODEL) \
        --tokenizer=$(MODEL) \
        --backend=vllm \
        --gsp-num-groups=$(GSP_NUM_GROUPS) \
        --gsp-prompts-per-group=$(GSP_PROMPTS_PER_GROUP) \
        --gsp-system-prompt-len=$(GSP_SYSTEM_PROMPT_LEN) \
        --gsp-question-len=$(GSP_QUESTION_LEN) \
        --gsp-output-len=$(GSP_OUTPUT_LEN) \
        --request-rate=800 \
        --max-concurrency=300 \
        --seed 42
    env:
    - name: IP
      value: "34.162.66.198" # Replace with the external IP of your deployed service
    - name: PORT
      value: "80"
    - name: MODEL
      value: "Qwen/Qwen3-235B-A22B-Instruct-2507-FP8"
    - name: HF_TOKEN
      valueFrom:
        secretKeyRef:
          name: hf-token-secret
          key: token
    - name: GSP_NUM_GROUPS
      value: "100"
    - name: GSP_PROMPTS_PER_GROUP
      value: "30"
    - name: GSP_SYSTEM_PROMPT_LEN
      value: "16384"
    - name: GSP_QUESTION_LEN
      value: "128"
    - name: GSP_OUTPUT_LEN
      value: "256"
  restartPolicy: Never
