# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# pipeline-name: KV Cache Offload
# pipeline-type: feature support matrix
steps:
  - label: "${TPU_VERSION:-tpu6e} Correctness tests for KV Cache Offload"
    key: "${TPU_VERSION:-tpu6e}KV_Cache_Offload_CorrectnessTest"
    soft_fail: true
    env:
      USE_V6E8_QUEUE: "True"
      VLLM_LOG_LEVEL: "INFO"
    agents:
      queue: tpu_v6e_8_queue
    commands:
      - |
        .buildkite/scripts/run_in_docker.sh \
          python3 -m pytest -s -v /workspace/tpu_inference/tests/offload/tpu_offload_accuracy_test.py
  - label: "${TPU_VERSION:-tpu6e} Record correctness test result for KV Cache Offload"
    key: "${TPU_VERSION:-tpu6e}record_KV_Cache_Offload_CorrectnessTest"
    depends_on: "${TPU_VERSION:-tpu6e}KV_Cache_Offload_CorrectnessTest"
    env:
      CI_TPU_VERSION: "${TPU_VERSION:-tpu6e}"
      CI_TARGET: "KV Cache Offload"
      CI_STAGE: "CorrectnessTest"
      CI_CATEGORY: "feature support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TPU_VERSION:-tpu6e}KV_Cache_Offload_CorrectnessTest

  - label: "${TPU_VERSION:-tpu6e} Performance tests for KV Cache Offload"
    key: "${TPU_VERSION:-tpu6e}KV_Cache_Offload_PerformanceTest"
    depends_on: "${TPU_VERSION:-tpu6e}record_KV_Cache_Offload_CorrectnessTest"
    soft_fail: true
    agents:
      queue: tpu_v6e_8_queue
    commands:
      - |
        .buildkite/scripts/run_in_docker.sh \
          python3 -m pytest -s -v /workspace/tpu_inference/tests/offload/tpu_offload_performance_test.py
  - label: "${TPU_VERSION:-tpu6e} Record performance test result for KV Cache Offload"
    key: "${TPU_VERSION:-tpu6e}record_KV_Cache_Offload_PerformanceTest"
    depends_on: "${TPU_VERSION:-tpu6e}KV_Cache_Offload_PerformanceTest"
    env:
      CI_TPU_VERSION: "${TPU_VERSION:-tpu6e}"
      CI_TARGET: "KV Cache Offload"
      CI_STAGE: "PerformanceTest"
      CI_CATEGORY: "feature support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TPU_VERSION:-tpu6e}KV_Cache_Offload_PerformanceTest
