# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# pipeline-name: Multimodal Inputs
# pipeline-type: feature support matrix
steps:
  - label: "${TPU_VERSION:-tpu6e} Correctness tests for Multimodal Inputs"
    key: "${TPU_VERSION:-tpu6e}_Multimodal_Inputs_CorrectnessTest"
    soft_fail: true
    env:
      TPU_VERSION: "${TPU_VERSION:-tpu6e}"
    agents:
      queue: "${TPU_QUEUE_SINGLE:-tpu_v6e_queue}"
    commands:
      - .buildkite/scripts/run_in_docker.sh python3 -m pytest -s -v /workspace/tpu_inference/tests/e2e/test_multi_modal_inference.py
  - label: "${TPU_VERSION:-tpu6e} Record correctness test result for Multimodal Inputs"
    key: "${TPU_VERSION:-tpu6e}_record_Multimodal_Inputs_CorrectnessTest"
    depends_on: "${TPU_VERSION:-tpu6e}_Multimodal_Inputs_CorrectnessTest"
    env:
      CI_TPU_VERSION: "${TPU_VERSION:-tpu6e}"
      CI_TARGET: "Multimodal Inputs"
      CI_STAGE: "CorrectnessTest"
      CI_CATEGORY: "feature support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TPU_VERSION:-tpu6e}_Multimodal_Inputs_CorrectnessTest

  - label: "${TPU_VERSION:-tpu6e} Performance tests for Multimodal Inputs"
    key: "${TPU_VERSION:-tpu6e}_Multimodal_Inputs_PerformanceTest"
    depends_on: "${TPU_VERSION:-tpu6e}_record_Multimodal_Inputs_CorrectnessTest"
    soft_fail: true
    agents:
      queue: "${TPU_QUEUE_SINGLE:-tpu_v6e_queue}"
    commands:
      - .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_inference/tests/e2e/benchmarking/mm_bench.sh
  - label: "${TPU_VERSION:-tpu6e} Record performance test result for Multimodal Inputs"
    key: "${TPU_VERSION:-tpu6e}_record_Multimodal_Inputs_PerformanceTest"
    depends_on: "${TPU_VERSION:-tpu6e}_Multimodal_Inputs_PerformanceTest"
    env:
      CI_TPU_VERSION: "${TPU_VERSION:-tpu6e}"
      CI_TARGET: "Multimodal Inputs"
      CI_STAGE: "PerformanceTest"
      CI_CATEGORY: "feature support matrix"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TPU_VERSION:-tpu6e}_Multimodal_Inputs_PerformanceTest
