# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# pipeline-name: moonshotai/Kimi-K2.6
# pipeline-type: text-only
steps:
  - label: "${TPU_VERSION:-tpu6e} Unit tests for moonshotai/Kimi-K2.6"
    key: "${TPU_VERSION:-tpu6e}_moonshotai_Kimi-K2_6_UnitTest"
    soft_fail: true
    agents:
      queue: "${TPU_QUEUE_MULTI:-tpu_v6e_queue}"
    commands:
      - |
        if [ "${TPU_VERSION:-tpu6e}" = "tpu6e" ]; then
          buildkite-agent meta-data set "${TPU_VERSION:-tpu6e}_moonshotai_Kimi-K2_6_UnitTest" "not enough HBM"
        else
          .buildkite/scripts/run_in_docker.sh \
            bash /workspace/tpu_inference/tests/e2e/benchmarking/mlperf.sh -m "gs://tpu-commons-ci/moonshootai/kimi/2.6" -t 2750
        fi
    env:
      NEW_MODEL_DESIGN: "1"
      SKIP_ACCURACY_TESTS: "False"
      VLLM_MLA_DISABLE: "0"
      MOE_REQUANTIZE_BLOCK_SIZE: "512"
      MOE_REQUANTIZE_WEIGHT_DTYPE: "fp4"
      MODEL_IMPL_TYPE: "vllm"
      USE_V7X8_QUEUE: "True"

  - label: "${TPU_VERSION:-tpu6e} Record unit test result for moonshotai/Kimi-K2_6"
    key: "${TPU_VERSION:-tpu6e}_record_moonshotai_Kimi-K2_6_UnitTest"
    depends_on: "${TPU_VERSION:-tpu6e}_moonshotai_Kimi-K2_6_UnitTest"
    env:
      CI_TPU_VERSION: "${TPU_VERSION:-tpu6e}"
      CI_TARGET: "moonshotai/Kimi-K2.6"
      CI_STAGE: "UnitTest"
      CI_CATEGORY: "text-only"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TPU_VERSION:-tpu6e}_moonshotai_Kimi-K2_6_UnitTest

  - label: "${TPU_VERSION:-tpu6e} Accuracy for moonshotai/Kimi-K2.6"
    key: "${TPU_VERSION:-tpu6e}_moonshotai_Kimi-K2_6_Accuracy"
    depends_on: "${TPU_VERSION:-tpu6e}_record_moonshotai_Kimi-K2_6_UnitTest"
    soft_fail: true
    agents:
      queue: cpu  # TODO: replace with execution environment
    env:
      TEST_MODEL: moonshotai/Kimi-K2.6
      TENSOR_PARALLEL_SIZE: "${TENSOR_PARALLEL_SIZE_SINGLE:-1}"
      MINIMUM_ACCURACY_THRESHOLD: 0  # TODO : replace 0 with your accuracy threshold
    commands:
      - |
        buildkite-agent meta-data set "${TPU_VERSION:-tpu6e}_moonshotai_Kimi-K2_6_Accuracy" "unverified"
  - label: "${TPU_VERSION:-tpu6e} Record accuracy result for moonshotai/Kimi-K2_6"
    key: "${TPU_VERSION:-tpu6e}_record_moonshotai_Kimi-K2_6_Accuracy"
    depends_on: "${TPU_VERSION:-tpu6e}_moonshotai_Kimi-K2_6_Accuracy"
    env:
      CI_TPU_VERSION: "${TPU_VERSION:-tpu6e}"
      CI_TARGET: "moonshotai/Kimi-K2.6"
      CI_STAGE: "Accuracy/Correctness"
      CI_CATEGORY: "text-only"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TPU_VERSION:-tpu6e}_moonshotai_Kimi-K2_6_Accuracy

  - label: "${TPU_VERSION:-tpu6e} Performance benchmarks for moonshotai/Kimi-K2.6"
    key: "${TPU_VERSION:-tpu6e}_moonshotai_Kimi-K2_6_Benchmark"
    depends_on: "${TPU_VERSION:-tpu6e}_record_moonshotai_Kimi-K2_6_Accuracy"
    soft_fail: true
    agents:
      queue: cpu  # TODO: replace with execution environment
    env:
      TEST_MODEL: moonshotai/Kimi-K2.6
      TENSOR_PARALLEL_SIZE: "${TENSOR_PARALLEL_SIZE_SINGLE:-1}"
      MINIMUM_THROUGHPUT_THRESHOLD: 0  # TODO : replace 0 with your performance threshold
    commands:
      - |
        buildkite-agent meta-data set "${TPU_VERSION:-tpu6e}_moonshotai_Kimi-K2_6_Benchmark" "unverified"
  - label: "${TPU_VERSION:-tpu6e} Record performance benchmark result for moonshotai/Kimi-K2.6"
    key: "${TPU_VERSION:-tpu6e}_record_moonshotai_Kimi-K2_6_Benchmark"
    depends_on: "${TPU_VERSION:-tpu6e}_moonshotai_Kimi-K2_6_Benchmark"
    env:
      CI_TPU_VERSION: "${TPU_VERSION:-tpu6e}"
      CI_TARGET: "moonshotai/Kimi-K2.6"
      CI_STAGE: "Benchmark"
      CI_CATEGORY: "text-only"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh ${TPU_VERSION:-tpu6e}_moonshotai_Kimi-K2_6_Benchmark
